### ISSUE TITLE
Missing isEqual

### ISSUE THREAD

**Issue by makabde** [ember-cli/ember-cli-shims#124]
I am wondering why the `isEqual` method is not available when using `import { isEqual } from 'ember-runtime';`.
Is there any other way to import it or should I import the entire Ember module first?

**Comment by n1ru4l** [comment]
There are even more missing exports.

https://github.com/ember-cli/ember-cli-shims/issues/37
https://github.com/ember-cli/ember-cli-shims/issues/36

**Comment by Turbo87** [comment]
This issue has been migrated to https://github.com/ember-cli/ember-rfc176-data/issues/5
