### ISSUE TITLE
New module syntax and deprecations with addons

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli-shims#126]
Lots of addons still use the old syntax. We need a way to be able to support both without deprecations. What is the current recommendation for this? We will want addons to use the new modules, while supporting older Ember versions as well.

**Comment by rwjblue** [comment]
Sorry for the delayed response here.  The solution for addon authors is as laid out in https://github.com/ember-cli/ember-cli-shims/pull/127 and https://github.com/babel/ember-cli-babel/pull/159.  

Basic summary:

* older shims are deprecated as of ember-cli@2.15 (from ember-cli-shims@1.2.0)
* new / final shims are available as a polyfill via ember-cli-babel@6

Once https://github.com/babel/ember-cli-babel/pull/159 is published, addon authors should immediately update to using the new public modules API.

**Comment by rwwagner90** [comment]
Thanks @rwjblue! Anything I can help with and/or help document?

**Comment by rwjblue** [comment]
I would _really really_ love it if someone updated ember-modules-codemod to migrate "old shims" to the new ones...

**Comment by rwwagner90** [comment]
@rwjblue should we just add an `else` [here](https://github.com/ember-cli/ember-modules-codemod/blob/master/transform.js#L301) and do the conversion there? I have never worked with this jscodeshift stuff, so I'm a little out of my element 😂

**Comment by rwjblue** [comment]
Yes, that seems like a good place to start.

**Comment by Turbo87** [comment]
@rwwagner90 FYI https://github.com/ember-cli/ember-modules-codemod/issues/16

**Comment by rwwagner90** [comment]
@rwjblue I cannot seem to run the tests. I get this:

```
1)  final-boss.js input and output should match:
     Error: spawn /Users/rwwagner/ember-modules-codemod/test/../node_modules/.bin/jscodeshift ENOENT
      at exports._errnoException (util.js:1050:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
      at onErrorNT (internal/child_process.js:367:16)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

Any ideas?

**Comment by Turbo87** [comment]
@rwwagner90 in case you still have that issue it should be discussed in the ember-modules-codemod repo
