### ISSUE TITLE
Move into future "ember" addon

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli-shims#15]
- [ ] https://github.com/emberjs/ember.js/pull/13022

**Comment by Turbo87** [comment]
@stefanpenner if I understood the situation correctly this should ultimately be integrated in the `ember` addon itself, right?

**Comment by rwjblue** [comment]
Yes

**Comment by Turbo87** [comment]
should this be done similar to https://github.com/emberjs/data/pull/3995?

**Comment by Turbo87** [comment]
this idea has been replaced by https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill and https://github.com/babel/ember-cli-babel/pull/159
