### ISSUE TITLE
Deprecate NPM package

### ISSUE THREAD

**Issue by bmish** [ember-cli/ember-cli-shims#168]
Can a maintainer please run:

```
npm deprecate ember-cli-shims "See the README about migration instructions: https://github.com/ember-cli/ember-cli-shims"
```

From the README:

> **Note:  this project is deprecated.  If you are using these shims in your project you should migrate to the new modules api outlined in [RFC 176](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) as soon as you can.  More information on this topic in [the Ember 2.16 release blog post](https://emberjs.com/blog/2017/10/11/ember-2-16-released.html#toc_ember-js-modules-api).**

https://www.npmjs.com/package/ember-cli-shims

**Comment by Turbo87** [comment]
done ✅
