### ISSUE TITLE
Release update

### ISSUE THREAD

**Issue by sir-dunxalot** [ember-cli/ember-cli-shims#20]
The tests fix added by #18 has not been released yet. Ember CLI's reference to `"ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3"` pulls down the previous version of `test-shims.js`. This breaks `ember-cli-mocha` because the code in `test-shims.js` is trying to define `QUnit` when it doesn't exist.

Please release v0.0.4 so we can update Ember CLI's bower.json accordingly.

In the interim I will use master branch instead of a release.

**Comment by acorncom** [comment]
0.0.6 seems to be out at this point
