### ISSUE TITLE
Why is isArray called isEmberArray

### ISSUE THREAD

**Issue by amk221** [ember-cli/ember-cli-shims#27]
`isEmberArray` makes it sound like a plain array needs to _be an Ember Array_, but the tests for `isArray` say otherwise?

```
isEmberArray(Ember.A()); // true, great makes sense
isEmberArray([]); // true, expecting false 
```

**Comment by amk221** [comment]
Related https://github.com/emberjs/ember.js/pull/12103

**Comment by rwjblue** [comment]
Generally you should just use `Array.isArray`, you should only use `isEmberArray` if you specifically are looking for an Ember.Array (which is fairly rare).
