### ISSUE TITLE
Bower dependencies causing ember 2.0 issues

### ISSUE THREAD

**Issue by mike-post** [ember-cli/ember-cli-shims#28]
The bower.json file for this project lists the dependency
````
  "dependencies": {
    "ember": ">=1.4"
  }
````

This creates an issue once you upgrade to ember 2.0.0: executing `bower install` on your CI server results in bower forcing you to make a choice (due to incompatible versions) so your CI builds fail.

The resulting output of `bower install` is:
````
Unable to find a suitable version for ember, please choose one:
    1) ember#>=1.4 <2 which resolved to 1.13.8 and is required by ember-cli-shims#0.0.3, ember-load-initializers#0.1.5
    2) ember#> 1.5.0-beta.3 which resolved to 1.13.8 and is required by ember-resolver#0.1.18
    3) ember#2.0.0 which resolved to 2.0.0 and is required by crawler-ui
    4) ember#^2.0.0 which resolved to 2.0.0 and is required by ember-data#2.0.0-beta.2

Prefix the choice with ! to persist it to bower.json
````

Persisting your choice to the bower.json file is a valid work around for this issue, but it probably should not be required.

**Comment by stefanpenner** [comment]
> "dependencies": {
>     "ember": ">=1.4"
>   }

this expression shouldn't matter, (2 >= 1.3) === true

**Comment by mike-post** [comment]
Bower is nuts.  I've learned the hard way that it doesn't semver in the same way as npm.  Look at line 1 in the bower output I listed.  Both ember-cli-shims and ember-load-initializers are resolving to ember < 2. The ember-resolver project does it differently and doesn't create that constraint.  The difference is ember-resolver uses the `>` version operator while the others use the `>=` version operator.

**Comment by mike-post** [comment]
The simple fix is to change the operator in the bower.json. However, I have no idea what this code is doing and what impact that would have.  Hence no pull request.

**Comment by stefanpenner** [comment]
@mike-post i think all the needs to change is the bower.json dep entry itself

**Comment by wagenet** [comment]
This issue has been misdiagnosed. The issue is that the `>= 1.4` was added after the `0.0.3` tag. We just need to release `0.0.4`.

**Comment by stefanpenner** [comment]
> This issue has been misdiagnosed. The issue is that the >= 1.4 was added after the 0.0.3 tag. We just need to release 0.0.4.

ah, thats an easy fix. @wagenet got a sec to tag?

**Comment by wagenet** [comment]
@stefanpenner I do not believe I am.

**Comment by mike-post** [comment]
Sorry about that.  @wagenet is totally correct.  In looking at my bower_components directory, I see that ember-cli-shims lists the dependency `"ember": ">=1.4 <2"`.

**Comment by stefanpenner** [comment]
@wagenet ah, you where on the ember-cli team. You are now on the owners team.

**Comment by wagenet** [comment]
And fixed :)

**Comment by stefanpenner** [comment]
thanks sir
