### ISSUE TITLE
Ember.ObjectProxy should be exported

### ISSUE THREAD

**Issue by xtian** [ember-cli/ember-cli-shims#36]
Since `Ember.ObjectProxy` is [now flagged as public](https://github.com/emberjs/ember.js/pull/11599), it should be available through a module shim as well.

**Comment by topaxi** [comment]
I was just looking for this one too.

**Comment by Turbo87** [comment]
this issue has been migrated to https://github.com/ember-cli/ember-rfc176-data/issues/3
