### ISSUE TITLE
Ember.PromiseProxyMixin should be exported

### ISSUE THREAD

**Issue by xtian** [ember-cli/ember-cli-shims#37]
This mixin is flagged as public: https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/mixins/promise_proxy.js#L88-L89

**Comment by n1ru4l** [comment]
Ember.ObjectProxy is also missing

**Comment by Turbo87** [comment]
this issue has been migrated to https://github.com/ember-cli/ember-rfc176-data/issues/4
