### ISSUE TITLE
Could not find module `ember-data`

### ISSUE THREAD

**Issue by ballPointPenguin** [ember-cli/ember-cli-shims#48]
I don't think this is a bug with ember-cli-shims, but I spent a bit of time learning that if I stick with ember-cli-shims 0.6.0 the problem disappears.

I am making this issue in case it helps anyone else in a similar situation to narrow down the variables.

```
Uncaught Error: Could not find module `ember-data` imported from `active-model-adapter/active-model-adapter`
```

ember 1.13.13
ember-cli 1.13.15
ember-cli-shims 1.0.0
ember-data 1.13.16
active-model-adapter 2.0.3

reverting to ember-cli-shims 0.6.0 seems to resolve this issue for me.

**Comment by xtian** [comment]
@ballPointPenguin The `ember-data` shims were moved to Ember Data in version 2.3.0 of Ember Data and so were removed from version 0.1.0 of ember-cli-shims.

**Comment by ballPointPenguin** [comment]
@xtian that makes sense. I'll close this issue.

**Comment by dwickern** [comment]
I had the same issue using ember-cli 2.3.0 with ember-data 2.2.1. Maybe this could be documented somewhere. I didn't know to search the issues in this repo until I had solved the problem.

**Comment by rwjblue** [comment]
I am not opposed to asking the Ember Data team if they can release a few point releases of the npm package to backdate the warning, but there is not much more we can do here (since bower doesn't provide any hooks we can use to display warnings)...

**Comment by rwjblue** [comment]
@fivetanley / @bmac - What do you think?

**Comment by bmac** [comment]
I would be ok with backdating the warning. Unfortunately, I'm super swamped atm and likely won't have time to do that this week. If I forget about this feel free to give me a gentle reminder early next week (if @fivetanley doesn't get to it first).

**Comment by rwjblue** [comment]
I don't mind doing the work, I just wanted to see if you thought it was a good idea.
