### ISSUE TITLE
Ember.merge is depreciated as of Ember-cli 2.5.0

### ISSUE THREAD

**Issue by TristanToye** [ember-cli/ember-cli-shims#55]
I believe I have tracked down a depreciation warning to the `app-shims.js` using Ember.merge here:

     'ember-platform': {
        'assign':         Ember.merge,
        'create':         Ember.create,
        'defineProperty': Ember.platform.defineProperty,
        'hasAccessors':   Ember.platform.hasPropertyAccessors,
        'keys':           Ember.keys
      },

According to [this](http://emberjs.com/deprecations/v2.x/#toc_ember-merge) it seems like a simple change.

**Comment by stefanpenner** [comment]
its no longer merged, we reverted it. Will be addressed soon (or has been)

**Comment by rwjblue** [comment]
2.5.1 just released
