### ISSUE TITLE
Ember.Logger should be exported

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-cli-shims#56]
Seems to be missing!

**Comment by rwjblue** [comment]
I believe this may have been intentional, but we should probably add a shim for it until we officially deprecate upstream.

**Comment by rwwagner90** [comment]
What are we supposed to use other than Ember.Logger? Definitely missing this!

**Comment by gtb104** [comment]
Right, if this is going to be deprecated, what importable module _should_ we be using?

**Comment by rwjblue** [comment]
`Ember.Logger` was originally intended as a polyfill for `console` APIs. Since our supported browsers all have native `console` now (IE8 was the last IIRC) we don't need a polyfill any longer...

> what importable module should we be using?

`console`

**Comment by gtb104** [comment]
Gotcha!

**Comment by gtb104** [comment]
Although, I can say that there are times that I want to log some info without using `console` because my linter will yell at me. Of course, I can always temporarily disable the linter, but it was nice to not have to do that.
