### ISSUE TITLE
Ember.RSVP Export

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli-shims#58]
Ember.RSVP is a large hole in this package's exports. `ember-rsvp` seems like an obvious package name, though the fact that we have forked RSVP itself and re-exported it also lends the possibility that we should pick a different name altogether.

@rwjblue had some more thoughts on this, I believe.

**Comment by stefanpenner** [comment]
it is currently the module `rsvp`

**Comment by elwayman02** [comment]
👍  awesome to know that it's there (totally missed that last line), though I think it's still somewhat incorrect to called it `rsvp`, since it's not the same as the actual `rsvp` package.

**Comment by stefanpenner** [comment]
I think its fine. just like jQuery and other addons etc. just happens that ember brings it along.
