### ISSUE TITLE
Generate an easy to read list of all shims included from the source

### ISSUE THREAD

**Issue by pichfl** [ember-cli/ember-cli-shims#88]
While the code is obviously not made for this, it was a fun exercise to extract a markdown compatible listing of all the shims from this addon. I'm pretty sure this is a rather brutal way, but it works.

I haven't figured on the best way to do it, but this could easily be part of the publishing process of this addon to have a proper reference.

```js
function handlerFactory(path = '') {
	return {
		get(target, name) {
			return name in target? target[name] : `${path}.${name.toString()}`;
		},
	}
}

function mapEntries(obj, cb) {
	return Object.entries(obj).map(cb);
}

const obj = {};

function listEmberCliShims() {
	global.Ember = new Proxy([
		'inject',
		'Instrumentation',
		'platform',
		'run',
		'String',
		'computed',
		'Test',
	].reduce((acc, key) => {
		acc[key] = new Proxy({ _key: `Ember.${key}` }, handlerFactory(`Ember.${key}`));

		return acc;
	}, { _key: 'Ember' }), handlerFactory('Ember'));

	const defined = {};

	global.define = (name, [], cb) => {
		const val = cb();

		if (val.default && val.default._key) {
			val.default = val.default._key;
		}

		defined[name] = val;
	};

	global.self = {
		jQuery: 'self.jQuery',
	};

	require('ember-cli-shims/vendor/ember-cli-shims/app-shims');

	return defined;
}

function listEmberCliShimsAsMarkdown(shims) {
	return `# All shims provided by this addon

${mapEntries(shims, ([key, value]) =>
`## \`${key}\`

${mapEntries(value, ([k, v]) =>
`- \`${k}\` ${(v || '').toString()}`).join("\n")}



`
	).join('')}`;
}

console.log(listEmberCliShimsAsMarkdown(listEmberCliShims()));
```

----

Results via `node generate.js > results.md`

# All shims provided by this addon

## `ember`

- `default` Ember

## `ember-application`

- `default` Ember.Application

## `ember-array`

- `default` Ember.Array

## `ember-array/mutable`

- `default` Ember.MutableArray

## `ember-array/utils`

- `A` Ember.A
- `isEmberArray` Ember.isArray
- `wrap` Ember.makeArray

## `ember-component`

- `default` Ember.Component

## `ember-components/checkbox`

- `default` Ember.Checkbox

## `ember-components/text-area`

- `default` Ember.TextArea

## `ember-components/text-field`

- `default` Ember.TextField

## `ember-controller`

- `default` Ember.Controller

## `ember-controller/inject`

- `default` Ember.inject.controller

## `ember-controller/proxy`

- `default` Ember.ArrayProxy

## `ember-controllers/sortable`

- `default` Ember.SortableMixin

## `ember-debug`

- `log` Ember.debug
- `inspect` Ember.inspect
- `run` Ember.runInDebug
- `warn` Ember.warn

## `ember-debug/container-debug-adapter`

- `default` Ember.ContainerDebugAdapter

## `ember-debug/data-adapter`

- `default` Ember.DataAdapter

## `ember-deprecations`

- `deprecate` Ember.deprecate
- `deprecateFunc` Ember.deprecateFunc

## `ember-enumerable`

- `default` Ember.Enumerable

## `ember-evented`

- `default` Ember.Evented

## `ember-evented/on`

- `default` Ember.on

## `ember-globals-resolver`

- `default` Ember.DefaultResolver

## `ember-helper`

- `default` Ember.Helper
- `helper` 

## `ember-instrumentation`

- `instrument` Ember.Instrumentation.instrument
- `reset` Ember.Instrumentation.reset
- `subscribe` Ember.Instrumentation.subscribe
- `unsubscribe` Ember.Instrumentation.unsubscribe

## `ember-locations/hash`

- `default` Ember.HashLocation

## `ember-locations/history`

- `default` Ember.HistoryLocation

## `ember-locations/none`

- `default` Ember.NoneLocation

## `ember-map`

- `default` Ember.Map
- `withDefault` Ember.MapWithDefault

## `ember-metal/destroy`

- `default` Ember.destroy

## `ember-metal/events`

- `addListener` Ember.addListener
- `removeListener` Ember.removeListener
- `send` Ember.sendEvent

## `ember-metal/get`

- `default` Ember.get
- `getProperties` Ember.getProperties

## `ember-metal/mixin`

- `default` Ember.Mixin

## `ember-metal/observer`

- `default` Ember.observer
- `addObserver` Ember.addObserver
- `removeObserver` Ember.removeObserver

## `ember-metal/on-load`

- `default` Ember.onLoad
- `run` Ember.runLoadHooks

## `ember-metal/set`

- `default` Ember.set
- `setProperties` Ember.setProperties
- `trySet` Ember.trySet

## `ember-metal/utils`

- `aliasMethod` Ember.aliasMethod
- `assert` Ember.assert
- `cacheFor` Ember.cacheFor
- `copy` Ember.copy
- `guidFor` Ember.guidFor

## `ember-object`

- `default` Ember.Object

## `ember-owner/get`

- `default` Ember.getOwner

## `ember-owner/set`

- `default` Ember.setOwner

## `ember-platform`

- `assign` Ember.assign
- `create` Ember.create
- `defineProperty` Ember.platform.defineProperty
- `hasAccessors` Ember.platform.hasPropertyAccessors
- `keys` Ember.keys

## `ember-route`

- `default` Ember.Route

## `ember-router`

- `default` Ember.Router

## `ember-runloop`

- `default` Ember.run
- `begin` Ember.run.begin
- `bind` Ember.run.bind
- `cancel` Ember.run.cancel
- `debounce` Ember.run.debounce
- `end` Ember.run.end
- `join` Ember.run.join
- `later` Ember.run.later
- `next` Ember.run.next
- `once` Ember.run.once
- `schedule` Ember.run.schedule
- `scheduleOnce` Ember.run.scheduleOnce
- `throttle` Ember.run.throttle

## `ember-service`

- `default` Ember.Service

## `ember-service/inject`

- `default` Ember.inject.service

## `ember-set/ordered`

- `default` Ember.OrderedSet

## `ember-string`

- `camelize` Ember.String.camelize
- `capitalize` Ember.String.capitalize
- `classify` Ember.String.classify
- `dasherize` Ember.String.dasherize
- `decamelize` Ember.String.decamelize
- `fmt` Ember.String.fmt
- `htmlSafe` Ember.String.htmlSafe
- `loc` Ember.String.loc
- `underscore` Ember.String.underscore
- `w` Ember.String.w

## `ember-utils`

- `isBlank` Ember.isBlank
- `isEmpty` Ember.isEmpty
- `isNone` Ember.isNone
- `isPresent` Ember.isPresent
- `tryInvoke` Ember.tryInvoke
- `typeOf` Ember.typeOf

## `ember-computed`

- `default` Ember.computed
- `empty` Ember.computed.empty
- `notEmpty` Ember.computed.notEmpty
- `none` Ember.computed.none
- `not` Ember.computed.not
- `bool` Ember.computed.bool
- `match` Ember.computed.match
- `equal` Ember.computed.equal
- `gt` Ember.computed.gt
- `gte` Ember.computed.gte
- `lt` Ember.computed.lt
- `lte` Ember.computed.lte
- `alias` Ember.computed.alias
- `oneWay` Ember.computed.oneWay
- `reads` Ember.computed.reads
- `readOnly` Ember.computed.readOnly
- `deprecatingAlias` Ember.computed.deprecatingAlias
- `and` Ember.computed.and
- `or` Ember.computed.or
- `collect` Ember.computed.collect
- `sum` Ember.computed.sum
- `min` Ember.computed.min
- `max` Ember.computed.max
- `map` Ember.computed.map
- `sort` Ember.computed.sort
- `setDiff` Ember.computed.setDiff
- `mapBy` Ember.computed.mapBy
- `mapProperty` Ember.computed.mapProperty
- `filter` Ember.computed.filter
- `filterBy` Ember.computed.filterBy
- `filterProperty` Ember.computed.filterProperty
- `uniq` Ember.computed.uniq
- `union` Ember.computed.union
- `intersect` Ember.computed.intersect

## `ember-test`

- `default` Ember.Test

## `ember-test/adapter`

- `default` Ember.Test.Adapter

## `ember-test/qunit-adapter`

- `default` Ember.Test.QUnitAdapter

## `jquery`

- `default` self.jQuery

## `rsvp`

- `default` Ember.RSVP

**Comment by rwjblue** [comment]
Neat!

**Comment by pichfl** [comment]
@rwjblue 🎉 Thanks!

I updated to code so rogue symbol definitions no longer show in the output. If someone points me in the right direction, I'm happy to make a pull request so this can be included. Otherwise running it by hand does the job as well.
