### ISSUE TITLE
Incorrect AMD Module Definitions

### ISSUE THREAD

**Issue by Coburn37** [ember-cli/ember-cli-shims#89]
I have a Webpack module with a UMD loader front-end that has an external jQuery as a dependency. Due to [this line](https://github.com/ember-cli/ember-cli-shims/blob/master/vendor/ember-cli-shims/app-shims.js#L259) in this module, jQuery is not passed to the AMD factory function properly and I get errors in my application. This also only happens when `define.amd` is true which is what happens when using [this feature](https://github.com/ember-cli/ember-cli/commit/8c84c6c6188cddb35fb6723f50c9f229439073b3) introduced into Ember v2.9.0. Here's an explanation for why this is happening.

Webpack's UMD loader looks like this (in my application that requires an external jQuery)

```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("jquery"));
	else if(typeof define === 'function' && define.amd)
		define(["jquery"], factory);
	else if(typeof exports === 'object')
		exports["mySubModule"] = factory(require("jquery"));
	else
		root["myApp"] = root["myApp"] || {}, root["myApp"]["mySubModule"] = factory(root["jQuery"]);
})
```

which in the case of Ember, where there is only an AMD loader (also dependent on using [the feature described above](https://github.com/ember-cli/ember-cli/commit/8c84c6c6188cddb35fb6723f50c9f229439073b3) which defines `define.amd`)  boils down to `define(["jquery"], factory);`. As generated by webpack, the factory is supposed to be passed the jQuery module [as per the RequireJS AMD docs](http://requirejs.org/docs/whyamd.html#definition). To quote their docs for the loading process (emphasis mine)...

> * Register the factory function by calling define(), instead of immediately executing it.
> * Pass dependencies as an array of string values, do not grab globals.
> * Only execute the factory function once all the dependencies have been loaded and executed.
> * **Pass the dependent modules as arguments to the factory function.**

The problem is that with this module, it defines jQuery as an ES6 module. When the factory function is called, it is passed an object that looks like...

```
{
    __esModule : true,
    default : $
}
```

...which is not equivalent to the jQuery library. I would have to do $["default"] to get jQuery. If an AMD loader is not present, then webpack works just fine as the last UMD loader line will get jQuery off of `window` no problem.

My thoughts, from reading the RequireJS docs, is that Ember is not correctly passing jQuery. But if you think this is a webpack issue I can take this over there.

**Comment by Turbo87** [comment]
`ember-cli-shims` does currently not attempt to support Webpack and since it is in the process of being deprecated completely I don't think working on it would make much sense at this point. I'm closing this issue due to these reasons.

**Comment by kernel-io** [comment]
@Turbo87 the OP mistakenly put this in this directory, he is talking about the vendor shimming feature of ember-cli proper, not the ember-cli-shims library.
